

export const GET_MENTORS="GET_MENTORS";
export const GET_MENTOR="GET_MENTOR";
export const PUT_MENTOR="PUT_MENTOR";
export const POST_MENTORS="POST_MENTORS";
export const DELETE_MENTOR="DELETE_MENTOR";
export const MENTORS_DATA_LOADING="MENTORS_DATA_LOADING";

export const SET_SIGNUP_FLAG="SET_SIGNUP_FLAG";
export const SET_UPDATED_DATE="SET_UPDATED_DATE";


export const GET_STUDENTS="GET_STUDENTS";
export const GET_STUDENT="GET_STUDENT";
export const PUT_STUDENT="PUT_STUDENT";
export const POST_STUDENTS="POST_STUDENTS";
export const DELETE_STUDENT="DELETE_STUDENT";
export const DATA_LOADING="DATA_LOADING";

export const LOGIN_ACTION="LOGIN_ACTION";
export const LOGOUT_ACTION="LOGOUT_ACTION";

export const POST_ERROR="POST_ERROR";
export const CLOSE_ERROR="CLOSE_ERROR";

export const GET_PROJECTS="GET_PROJECTS";
export const GET_PROJECT="GET_PROJECT";
export const CREATE_PROJECT="CREATE_PROJECT";
export const PATCH_PROJECT="PATCH_PROJECT";
export const DELETE_PROJECT="DELETE_PROJECT";
export const GET_PENDINGACTION_PROJECTS="GET_PENDINGACTION_PROJECTS";



